(in-package :igo)

(delete-package-nickname :igo.varied-byte-stream)
(delete-package-nickname :igo.code-stream)
(delete-package-nickname :igo.trie)
(delete-package-nickname :igo.matrix)
(delete-package-nickname :igo.char-category)
(delete-package-nickname :igo.viterbi-node)
(delete-package-nickname :igo.word-dic)
(delete-package-nickname :igo.unknown)
